from enum import Enum

# We define our constant responses with a class inhirets form Enum class to have its properties
class ResponseSignal(Enum):

    # Defining our constants responses to be used in many situations
    FILE_TYPE_NOT_SUPPORTED: str = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED: str = "FILE_SIZE_EXCEEDED"
    FILE_VALIDATE_SUCCEEDED: str = "FILE_VALIDATE_SUCCEEDED"
    FILE_UPLOAD_SUCCEEDED: str = "FILE_UPLOAD_SUCCEEDED"
    FILE_UPLOAD_FAILED: str = "FILE_UPLOAD_FAILED"
    FILE_PROCESS_FAILED: str = "NO_FILES_FOUND"
    FILE_NOT_FOUND: str = "No_FILE_WITH_FILE_ID"

    PROCESS_FAILED: str = "PROCESS_FAILED"
    PROCESS_SUCCEEDED: str = "PROCESS_SUCCEEDED"

    MONGODB_CONNECTION_FAILED: str = "MONGODB_CONNECTION_FAILED"
    
    INSERT_INTO_VECTORDB_ERROR: str = "INSERT_INTO_VECTORDB_FAILED"
    INSERT_INTO_VECTORDB_SUCCEEDED: str = "INSERT_INTO_VECTORDB_SUCCEEDED"
    GET_VECTORDB_COLLECTION_INFO_SUCCEEDED: str = "GET_VECTORDB_COLLECTION_INFO_SUCCEEDED"
    SEARCH_VECTORDB_COLLECTION_SUCCEEDED: str = "SEARCH_VECTORDB_COLLECTION_SUCCEEDED"
    
    RAG_ANSWER_ERROR: str = "rag_answer_error"
    RAG_ANSWER_SUCCESS: str = "rag_answer_success"

